[package]
name = "encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
dlopen2 = "0.7.0"
nwd = { package = "native-windows-derive", version = "1.0.5" }
nwg = { package = "native-windows-gui", version = "1.0.13" }
